templateRepository:
  gitProvider: deepak_git
  path: creepy-pirate/template-check
  branch: actualtemplateToPublish
  templateFolder: ./

publishTemplate:
  namespace: newTemplates
  name: myPipelineTemplate
  version: 1.0.0
  pipelineName: PublishTemplateUnique
  jfrogAccessTokenIntegration: jpat_deepak
  runtime:
    custom:
      name: "releases-docker.jfrog.io/jfrog/pipelines-u18node"
      tag: "16"
